version: "3"
services:
  vue:
    image: centos7:7.7.1908
    build:
      context: ./vue-conf
    ports:
      - 80:80
    stdin_open: true 
    links:
      - swagger-ui
      - redis
      - api
    volumes:
      - "./vue:/var/www/html"
    container_name: "vue"
  swagger-editor:
    image: centos7/base:1                                 
    build:
      context: ./swagger-conf
    ports: 
      - 8080:8080
    stdin_open: true 
    volumes:
      - "./swagger-editor:/var/api"
    container_name: "swagger-editor"  
  swagger-ui:
    image: centos7/base:1                                 
    build:
      context: ./swagger-conf
    ports: 
      - 8081:8081
    stdin_open: true 
    volumes:
      - "./swagger-ui:/var/api"
    container_name: "swagger-ui"
  api:
    image: centos7:7.7.1908                                 
    build:
      context: ./springboot-conf
    ports: 
      - 81:81
    links:
      - mysql
      - redis
    volumes:
      - "./springboot:/var/www/html"
    container_name: "api_srv"
    stdin_open: true 
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=BOOSTER_DATA
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    container_name: "mysql"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass root
    volumes:
      - ./redis:/data
    container_name: "redis"
